create_content_strategy:
  description: >
    Create a content strategy for church social media accounts that includes:
    1. Content themes and topics for the week/month
    2. Platform-specific content adaptations (Instagram, Facebook, etc.)
    3. Posting schedule and frequency
    4. Engagement strategies
    Content requirements: {requirements}
  expected_output: >
    A detailed content strategy document containing:
    - Content themes and topics
    - Platform-specific content plans
    - Posting schedule
    - Engagement tactics
    - Success metrics

review_and_approve_content:
  description: >
    Review the processed content for:
    1. Theological accuracy and biblical soundness
    2. Social media best practices
    3. Platform-specific formatting
    4. Engagement potential
    Content to review: {content}
  expected_output: >
    A review report containing:
    - Approval status
    - Any required modifications
    - Platform-specific formatting suggestions
    - Recommended posting time and hashtags

coordinate_content_flow:
  description: >
    Manage the workflow of content creation and processing by:
    1. Assigning tasks to appropriate team members
    2. Setting deadlines and priorities
    3. Ensuring quality control
    4. Maintaining content calendar
  expected_output: >
    A workflow management report including:
    - Task assignments
    - Timeline
    - Quality control checkpoints
    - Content calendar updates

classify_content:
  description: >
    Analyze the provided content and determine its category:
    1. Full Sermon: Complete sermon transcripts or recordings
    2. Post Idea: Social media content or short devotional messages
    3. Bible Verse: Scripture references or verse-based content
    4. Other: Any content that doesn't fit the above categories
    
    Provide a detailed explanation for your classification and recommend which specialized agents should process it.
    Content: {content}
  expected_output: >
    A JSON object containing:
    - category: The determined content type
    - explanation: Reasoning behind the classification
    - recommended_agents: List of agents available on your crewthat should process this content

verify_biblical_content:
  description: >
    Review the content for biblical accuracy and provide theological insights.
    Verify any scripture references, doctrinal statements, or theological concepts.
    Identify any areas that need clarification or correction.
  expected_output: >
    A detailed analysis including:
    - Biblical accuracy assessment
    - Verified scripture references
    - Theological insights
    - Any recommended clarifications

create_summary:
  description: >
    Create a concise summary of the content that captures the main points,
    key scriptures, and central message. Include any action items or
    practical applications mentioned.
  expected_output: >
    A structured summary containing:
    - Main theme
    - Key points
    - Scripture references
    - Practical applications

create_instagram_story:
  description: >
    Create engaging Instagram Story content that includes:
    1. Story format and layout
    2. Interactive elements (polls, quizzes, questions)
    3. Visual style guidelines
    4. Call-to-action elements
    Content: {content}
  expected_output: >
    A detailed Instagram Story plan containing:
    - Story structure and flow
    - Interactive element details
    - Visual style specifications
    - Engagement elements

create_instagram_post:
  description: >
    Create an engaging Instagram Post that includes:
    1. Post type (carousel, single image, IGTV)
    2. Content theme and message
    3. Visual requirements
    4. Engagement strategy
    Content: {content}
  expected_output: >
    A complete Instagram Post plan containing:
    - Post type and format
    - Content structure
    - Visual requirements
    - Engagement elements

generate_image_prompt:
  description: >
    Create a detailed prompt for image generation that:
    1. Captures the essence of the message
    2. Specifies visual style and elements
    3. Includes color scheme and mood
    4. Describes composition and layout
    Content: {content}
  expected_output: >
    A detailed image generation prompt including:
    - Main subject description
    - Style and artistic direction
    - Color palette and mood
    - Composition guidelines

create_image:
  description: >
    Generate an image using DALL-E based on the provided prompt that:
    1. Matches the specified style and elements
    2. Follows brand guidelines
    3. Maintains appropriate dimensions
    4. Ensures high quality output
  expected_output: >
    A high-quality image that includes:
    - Generated image file
    - Image dimensions
    - Style confirmation
    - Quality assessment

create_caption:
  description: >
    Create an engaging caption that:
    1. Incorporates relevant Bible verse(s)
    2. Includes compelling call-to-action
    3. Uses appropriate hashtags
    4. Maintains brand voice
    Content: {content}
  expected_output: >
    A complete caption package containing:
    - Main caption text
    - Bible verse reference
    - Call-to-action
    - Relevant hashtags
